name: Linux x64 Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish the project
        run: dotnet publish -c Release -r linux-x64

      - name: Archive the published output
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: GalArc-ci-linux-x64
          path: GalArc/bin/Release/net9.0/linux-x64/publish